# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/University/4course/SystemOnTheChip/Labs/3/SoC_Lab3/integration/lab_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/4course/SystemOnTheChip/Labs/3/SoC_Lab3/integration/lab_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/University/4course/SystemOnTheChip/Labs/3/SoC_Lab3/integration/lab_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/4course/SystemOnTheChip/Labs/3/SoC_Lab3/integration/lab_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
